spring:
  application:
    name: schoolmanagement
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always

# Logging configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
